import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import Navbar from '../components/Navbar';
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider options={{ enableCssLayer: true }}>
          <NextTopLoader color="#DEF2FF" height={2} showSpinner={false} />
          <Navbar />
          {children}
        </AppRouterCacheProvider>
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  );
}
